// Master Product Catalog List (Architecture Blueprint)
// Core Categories: SERUM_LAB, TARGET_REPAIR, DERMA_SHIELD

const products = [
    {
        id: 1,
        name: "RETINOL_SYNAPSE 0.5%",
        category: "SERUM_LAB",
        categoryLabel: "SERUMS & AMPOULES",
        price: 1799,
        rating: 4.9,
        reviewsCount: 128,
        skinTypes: ["Dry", "Oily", "Combo"],
        targetConcerns: ["Aging", "Fine Lines", "Texture"],
        description: "Micro-encapsulated stable retinol built to stimulate deep cell turnover cycles and smooth fine lines.",
        longDescription: "Advanced clinical delivery system encapsulates 0.5% pure retinol to maximize cellular turnover while minimizing surface erythema and irritation. Infused with biomimetic soothing peptides to buffer active potency.",
        image: "serum_bottle.png",
        badge: "BESTSELLER",
        ingredients: ["0.5% Encapsulated Retinol", "Biomimetic Peptides", "Squalane", "Vitamin E", "Bisabolol"],
        efficacy: { firmness: "94%", texture: "96%", glow: "91%" },
        usage: "Apply 2-3 drops to clean, dry skin in the PM. Follow with barrier repair cream. Use SPF daily."
    },
    {
        id: 2,
        name: "VITAMIN_C_RADIANCE_15%",
        category: "SERUM_LAB",
        categoryLabel: "SERUMS & AMPOULES",
        price: 1599,
        rating: 4.8,
        reviewsCount: 94,
        skinTypes: ["Dry", "Combo"],
        targetConcerns: ["Aging", "Dullness", "Hyperpigmentation"],
        description: "High-potency L-Ascorbic acid matrix designed to neutralize free radicals and fade hyperpigmentation.",
        longDescription: "Formulated with a highly stable 15% triple-vitamin C complex (L-Ascorbic Acid, THD Ascorbate, and Ferulic Acid) to dramatically brighten dull skin, diminish dark spots, and shield against environmental stress.",
        image: "serum_bottle.png",
        badge: "CLINICAL GRADE",
        ingredients: ["15% L-Ascorbic Acid", "Ferulic Acid", "Ergothioneine", "Hyaluronic Acid", "Kakadu Plum Extract"],
        efficacy: { brightness: "98%", evenTone: "93%", antioxidant: "99%" },
        usage: "Apply 3-5 drops to face and neck in the AM before sunscreen."
    },
    {
        id: 3,
        name: "PEPTIDE_AMPLIFIER_COMPLEX",
        category: "SERUM_LAB",
        categoryLabel: "SERUMS & AMPOULES",
        price: 1999,
        rating: 4.9,
        reviewsCount: 156,
        skinTypes: ["Dry", "Combo"],
        targetConcerns: ["Aging", "Elasticity", "Wrinkles"],
        description: "Multi-chain amino acid complex designed to improve skin elasticity and support natural collagen synthesis.",
        longDescription: "An intensive cellular matrix formula featuring 5 highly specialized peptide chains designed to mimic the skin's natural growth factors. Visibly firms, lifts, and restores youthful plumpness to policing depleted skin.",
        image: "serum_bottle.png",
        badge: "AWARD WINNER",
        ingredients: ["Matrixyl 3000", "Argireline", "Copper Peptides", "Amino Acid Blend", "Glycerin"],
        efficacy: { elasticity: "97%", wrinkleReduction: "92%", hydration: "95%" },
        usage: "Gently press 3 drops into skin AM and PM after cleansing."
    },
    {
        id: 4,
        name: "SALICYLIC_MATRIX 2%",
        category: "TARGET_REPAIR",
        categoryLabel: "ACNE CORRECTORS",
        price: 1499,
        rating: 4.7,
        reviewsCount: 112,
        skinTypes: ["Oily", "Combo"],
        targetConcerns: ["Acne", "Pores", "Sebum"],
        description: "Advanced lipid-soluble BHA compound engineered to penetrate deep into pore pathways and clear stubborn acne.",
        longDescription: "Utilizes a time-release 2% Salicylic Acid matrix combined with purifying botanical astringents to dissolve impacted sebum, clarify congested pore linings, and prevent future breakout cycles without dehydrating the skin.",
        image: "acne_corrector.png",
        badge: "POPULAR",
        ingredients: ["2% Salicylic Acid (BHA)", "Tea Tree Hydrosol", "Zinc PCA", "Green Tea Extract", "Allantoin"],
        efficacy: { poreClarity: "96%", blemishReduction: "94%", oilControl: "92%" },
        usage: "Apply a thin layer to congested areas 1-2 times daily."
    },
    {
        id: 5,
        name: "BENZOYL_OXIDE_SPOT_SHIELD",
        category: "TARGET_REPAIR",
        categoryLabel: "ACNE CORRECTORS",
        price: 999,
        rating: 4.8,
        reviewsCount: 88,
        skinTypes: ["Oily"],
        targetConcerns: ["Acne", "Blemishes"],
        description: "Emergency fast-acting spot treatment designed to target acne-causing bacteria directly on contact.",
        longDescription: "A targeted micro-emulsion spot treatment delivering micronized benzoyl peroxide directly to the follicular core. Rapidly reduces blemish size, erythema, and local inflammation within 12 hours.",
        image: "acne_corrector.png",
        badge: "FAST ACTING",
        ingredients: ["Micronized Benzoyl Peroxide", "Niacinamide", "Licorice Root Extract", "Colloidal Oatmeal"],
        efficacy: { speedOfReduction: "95%", soothing: "89%", rednessReduction: "93%" },
        usage: "Dab directly onto active blemishes at night. Do not apply to entire face."
    },
    {
        id: 6,
        name: "AZELAIC_CELL_CORRECTOR_10%",
        category: "TARGET_REPAIR",
        categoryLabel: "ACNE CORRECTORS",
        price: 1350,
        rating: 4.9,
        reviewsCount: 142,
        skinTypes: ["Dry", "Oily", "Combo"],
        targetConcerns: ["Acne", "Redness", "Scars", "Hyperpigmentation"],
        description: "Dicarboxylic acid compound built to target dark marks left behind by acne while soothing skin inflammation.",
        longDescription: "High-purity 10% Azelaic Acid gel-cream designed to mitigate post-inflammatory hyperpigmentation (PIH), calm persistent rosacea-prone redness, and refine uneven textural anomalies.",
        image: "acne_corrector.png",
        badge: "DERM RECOMMENDED",
        ingredients: ["10% Pure Azelaic Acid", "Centella Asiatica", "Madecassoside", "Hyaluronic Acid"],
        efficacy: { scarFading: "94%", rednessRelief: "97%", skinSmoothness: "95%" },
        usage: "Apply evenly to face AM and PM. Can be layered under moisturizer."
    },
    {
        id: 7,
        name: "HYALURONIC_CELL_INFUSION",
        category: "DERMA_SHIELD",
        categoryLabel: "BARRIER REPAIR",
        price: 1299,
        rating: 4.8,
        reviewsCount: 170,
        skinTypes: ["Dry", "Combo"],
        targetConcerns: ["Hydration", "Dehydration", "Flaking"],
        description: "Multi-depth hyaluronic acid booster designed to bind moisture molecules directly into dehydrated skin layers.",
        longDescription: "An advanced hydro-matrix combining 4 distinct molecular weights of Hyaluronic Acid with cross-linked polyglutamic acid. Delivers immediate surface plumping while creating a deep sub-dermal moisture reservoir.",
        image: "cream_jar.png",
        badge: "INTENSE HYDRATION",
        ingredients: ["Quad-Weight Hyaluronic Acid", "Polyglutamic Acid", "Vitamin B5 (Panthenol)", "Aloe Leaf Juice"],
        efficacy: { moistureBinding: "99%", plumping: "96%", barrierSupport: "94%" },
        usage: "Apply 3-4 drops to damp skin immediately after cleansing or misting."
    },
    {
        id: 8,
        name: "NIACINAMIDE_MATTE_SHIELD 10%",
        category: "DERMA_SHIELD",
        categoryLabel: "BARRIER REPAIR",
        price: 1199,
        rating: 4.7,
        reviewsCount: 134,
        skinTypes: ["Oily"],
        targetConcerns: ["Hydration", "Sebum Control", "Pores"],
        description: "Ultra-lightweight Vitamin B3 formula engineered to lock in deep hydration while actively shrinking visible pore size.",
        longDescription: "A specialized barrier serum tailored for lipid-rich skin. 10% Niacinamide pairs with balancing Zinc PCA to regulate sebum excretion, minimize enlarged pore appearance, and strengthen the epidermal lipid barrier.",
        image: "cream_jar.png",
        badge: "OIL-FREE",
        ingredients: ["10% Niacinamide", "1% Zinc PCA", "Willow Bark Extract", "Prebiotic Ferment"],
        efficacy: { sebumRegulation: "95%", poreRefinement: "93%", barrierIntegrity: "96%" },
        usage: "Smooth over clean skin AM and PM before applying lightweight gel moisturizer."
    },
    {
        id: 9,
        name: "CERAMIDE_BARRIER_LOCK_2X",
        category: "DERMA_SHIELD",
        categoryLabel: "BARRIER REPAIR",
        price: 1650,
        rating: 5.0,
        reviewsCount: 210,
        skinTypes: ["Dry", "Combo"],
        targetConcerns: ["Hydration", "Damaged Barrier", "Sensitivity"],
        description: "Intense lipid cream enriched with pure Ceramides and Phytosphingosine to rebuild flaky, irritated skin barriers.",
        longDescription: "A luxurious, deeply restorative lipid emulsion featuring a 3:1:1 golden ratio of bio-identical Ceramides, natural Cholesterol, and Free Fatty Acids. Instantly halts trans-epidermal water loss (TEWL) and repairs compromised skin architecture.",
        image: "cream_jar.png",
        badge: "HOLY GRAIL",
        ingredients: ["Ceramide NP, AP, EOP", "Phytosphingosine", "Cholesterol", "Shea Butter", "Organic Jojoba Oil"],
        efficacy: { barrierRepair: "99%", flakingRelief: "100%", soothing: "98%" },
        usage: "Warm a pea-sized amount between palms and press gently into face and neck as the final skincare step."
    },
    // Additional Catalog Expansion Products to demonstrate 50-Product Architecture Blueprint
    {
        id: 10,
        name: "SQUALANE_OMEGA_ELIXIR",
        category: "DERMA_SHIELD",
        categoryLabel: "BARRIER REPAIR",
        price: 1450,
        rating: 4.8,
        reviewsCount: 65,
        skinTypes: ["Dry", "Combo"],
        targetConcerns: ["Hydration", "Damaged Barrier"],
        description: "100% plant-derived squalane infused with omega fatty acids to lock in moisture and calm reactivity.",
        longDescription: "Pure biocompatible sugarcane squalane fortified with Omega 3, 6, and 9 lipids. Provides weightless, non-comedogenic nourishment that mimics the skin's natural sebum.",
        image: "cream_jar.png",
        badge: "100% PURE",
        ingredients: ["Sugarcane Squalane", "Omega Fatty Acid Complex", "Tocopherol"],
        efficacy: { moistureLock: "97%", softness: "98%", soothing: "94%" },
        usage: "Apply 2 drops over moisturizer to seal in hydration."
    },
    {
        id: 11,
        name: "LACTIC_ACID_RESURFACER_8%",
        category: "SERUM_LAB",
        categoryLabel: "SERUMS & AMPOULES",
        price: 1650,
        rating: 4.7,
        reviewsCount: 82,
        skinTypes: ["Dry", "Combo"],
        targetConcerns: ["Aging", "Dullness", "Texture"],
        description: "Gentle AHA exfoliating serum designed to dissolve dead skin cells while boosting natural moisturizing factors.",
        longDescription: "Formulated with 8% Lactic Acid and soothing Tasmanian Pepperberry to provide effective, non-abrasive chemical exfoliation that reveals a radiant, glassy complexion.",
        image: "serum_bottle.png",
        badge: "GLOW BOOSTER",
        ingredients: ["8% Lactic Acid", "Tasmanian Pepperberry", "Hyaluronic Acid"],
        efficacy: { exfoliation: "95%", glow: "96%", hydration: "92%" },
        usage: "Apply 2-3 drops in the PM 2-3 times a week."
    },
    {
        id: 12,
        name: "CENTELLA_CALMING_AMPOULE",
        category: "TARGET_REPAIR",
        categoryLabel: "ACNE CORRECTORS",
        price: 1250,
        rating: 4.9,
        reviewsCount: 104,
        skinTypes: ["Oily", "Combo", "Dry"],
        targetConcerns: ["Acne", "Redness", "Sensitivity"],
        description: "Highly concentrated Centella Asiatica extract to rapidly pacify angry, inflamed, or sensitized skin.",
        longDescription: "100% pure Centella Asiatica extract harvested from Madagascar. Provides immediate thermal relief, reduces vascular redness, and accelerates blemish healing.",
        image: "acne_corrector.png",
        badge: "SOOTHING",
        ingredients: ["100% Centella Asiatica Extract"],
        efficacy: { calming: "99%", rednessReduction: "96%", healing: "95%" },
        usage: "Pat generous amount onto sensitized areas whenever needed."
    }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { products };
}
